### ISSUE TITLE
Ios clients are not able to join

### ISSUE THREAD

**Issue by Ferohers** [Gorodskih/docker_strongswan_ikev2_letsencrypt#2]
Hi,

Wish you a fantastic day. IOS clients sadly refuse to connect. 
I am an old school person so had little to no knowledge in docker. I guess the following setting may work with new IOS clients.

        ike=aes256gcm16-prfsha384-ecp384!
        esp=aes256gcm16-ecp384!

Note: it did not work.

**Comment by Gorodskih** [comment]
Hello. I am sorry but I don't have any Apple device to test connection.
Current accepted encryption options are very wide and should be supported by most of the clients.
But I can make them configurable when I will have time for that.

**Comment by Gorodskih** [comment]
Hi, @Ferohers !
I finally managed to update the project and setup builds.
Now you can set proposals in [docker-compose.yml](https://github.com/Gorodskih/docker_ikev2_letsencrypt/blob/main/docker-compose.yml) file by new environmental variables IKE_PROPOSALS and ESP_PROPOSALS.

Please try to setup container from scratch because I have even renamed the repository. README was also updated.
